### ISSUE TITLE
Suggestion: marketplace best deal command

### ISSUE THREAD

**Issue by TheCrazyInsanity** [alexemanuelol/rustPlusPlus#122]
search for the lowest item per item price e.g. search for lowest scrap per rifle ammo

**Comment by alexemanuelol** [comment]
This really is a matter of preference, items are worth different amounts for different people, and its not easy to compare value on different items.

Say someone is selling a rocket for 200 scrap and someone else is selling a rocket for 5 explosives, which one would be the "cheaper" option?

If you mean that there should be a command that finds the lowest quantity of currency for an item, I think it wont be useful enough since the currency could be practically anything...
