### ISSUE TITLE
Unable to update

### ISSUE THREAD

**Issue by undeci16** [alexemanuelol/rustPlusPlus#139]
When I run update.bat im getting "package-lock.json: needs merge"
"Could not successfully stash current changes"

Been having this issue for couple days now.

**Comment by PandeoF1** [comment]
If the package-lock.json needs a merge. It's because u have installed/updated a package. To patch this issues :

Create a backup of package-lock.json on you'r desktop (Not in the rustPlusPlus folder).
Empty package-lock.json and replace the content by the one on the repository :
https://github.com/alexemanuelol/rustPlusPlus/blob/master/package-lock.json

Try to update.

**Comment by undeci16** [comment]
It did not work copying the package-lock.json from which you sent, however I had another copy of rustplusplus, I copied over the package-lock.json from there and it worked. 
However I got this at the end, Is this normal or is there something I need to do? https://i.imgur.com/w4LJobm.png

**Comment by PandeoF1** [comment]
Yeah after rereading it seems stupid to have asked you to copy the last version of the package-lock because there must have been changes between your version and the last one. I should have told you to take the file of the same version that you have ^^. But this will at least guide you to patch this error.
So to fix the two errors you have now.
Make a copy of your configuration file 
Execute these two commands:
git restore -stage config/index.js
git restore -stage package-lock.json

Once you have done this you can re-configure the config/index.js file or create an .env file and use environment variables to avoid the same problem.

Example of ".env" file:
```env
RPP_DISCORD_CLIENT_ID=your_id
RPP_DISCORD_TOKEN=your_token
```

**Comment by undeci16** [comment]
Hm when trying to do
git restore -stage config/index.js
and
git restore -stage package-lock.json

It says "fatal: could not resolve tage"

**Comment by PandeoF1** [comment]
For  package-lock.json or config/index ?

**Comment by undeci16** [comment]
Both

**Comment by PandeoF1** [comment]
Press "git status" and screen me the output please

**Comment by undeci16** [comment]
https://i.imgur.com/txAjXdn.png

**Comment by PandeoF1** [comment]
Try:
```
git reset config/index.js
git reset package-lock.json
```

If you have nothing to lose you can do :
```
git reset --hard
```

This command will reset every file with a clean version (but will delete every changed file).

After that try to
```
git pull
```

**Comment by undeci16** [comment]
Hm does this help at all before I do the reset --hard? https://i.imgur.com/pVPNiHW.png

**Comment by PandeoF1** [comment]
Yes,
git add config/index.js
git add package-lock.json

**Comment by undeci16** [comment]
sweet the errors are gone from the status.
Now It wont run because of the index.js file it like doubled up the token stuff https://i.imgur.com/mwbkJAh.png, and since I couldn't restore it I just manually copied it from https://github.com/alexemanuelol/rustPlusPlus/blob/master/config/index.js.
Now all is working, thank you!!

**Comment by PandeoF1** [comment]
Don't worry, you can now close the issue if everything work as well ! ;)
