### ISSUE TITLE
Hosting this creature of god.

### ISSUE THREAD

**Issue by Falomaly** [alexemanuelol/rustplusplus#232]
Hi! I have tried 2 hosting services and both of them have a problem with Rust+ connection as i can understand. For some reason in hosting service bot spam something like "Timeout reached while waiting for response..." or something like that. All the discord features works fine, but in-game chat commands causes this error. Maybe you can recommend some hosting service, or this project strongly orientaited to work in PC only? Anyway thank you for this powerful project.

Also a few ideas from me:
Add /recycle [item] [quantity] command - /recycle Fuse 40 = you get ..... scrap etc., and it takes ..... time to recycle.
Time until the next Cargo ship, as i know it spawns every 2 hours.

**Comment by alexemanuelol** [comment]
Funnily enough, its not the first time I've been referred to as a god 😂

I haven't personally tried it on any hosting services. I've only had it on my PC, a laptop and on a RPi. You might get a better response in tue discord, I know several people host it through different services.

I think the recycle command could be a nice addition. Not so sure about the recycle time though... Not sure if I can find data on quantity of an item getting recycled every 5 seconds or whatever it is... You know what I mean? Like pipes gets recycled 2 at a time and rope 5 at a time etc...

I won't add the 'time left' till next cargo because that time is not the same always. It's somewhere between 1-3 hours

**Comment by PandeoF1** [comment]
Hi @Falomaly, can you give me a link to the both hosting services. Because it can come from the firewall of each hoster. In some VPS hoster their is a protection that kill all TCP/UDP connections that are too long.

Also if you can provide OS version, nodejs version.. :)

Did you try inside a docker or directly on the VM ?

**Comment by Falomaly** [comment]
Hi @PandeoF1! The first service is sparkedhost.com, ive tried here both  - bot hosting service and VM using docker. The second one is pebblehost.com.

**Comment by PandeoF1** [comment]
> Hi @PandeoF1! The first service is sparkedhost.com, ive tried here both - bot hosting service and VM using docker. The second one is pebblehost.com.

Did you use discord bot hosting on those or vps hosting ?

**Comment by Falomaly** [comment]
> > Hi @PandeoF1! The first service is sparkedhost.com, ive tried here both - bot hosting service and VM using docker. The second one is pebblehost.com.
> 
> Did you use discord bot hosting on those or vps hosting ?

https://prnt.sc/cOXyJ2u3nT3U - Sparked, Pebblehost only bothosting, but support answers me that their host do not support TS.

**Comment by alexemanuelol** [comment]
Added issues for research/craft etc...
Regarding suggestion for hosting I suggest asking in https://discord.gg/YtQMYYK2kM
