### ISSUE TITLE
[IDEA] Extend hoster priviledge

### ISSUE THREAD

**Issue by HandyS11** [alexemanuelol/rustplusplus#300]
Extend the HOSTER priviledge to add a server to every people register to the bot to improve user experience.

The fact that you need to change it manually with the /credential set_hoster  is boring

**Comment by alexemanuelol** [comment]
Allowing everyone to be hoster would just make the entire thing too complex. It's easier having one person being the "hoster".

Most users won't do the set_hoster too often so I don't see that as a problem.

**Comment by HandyS11** [comment]
I mean I'm part of a friend group of 5 or 6 people that plays Wipeout at 2 or 3 almost every day and it lasts for 3 or 4 days. The fact that the team members are always different means that we have to change the host almost every wipe.

**Comment by alexemanuelol** [comment]
I don't see that as a big issue. The Rust+ API have a restriction to only allow 5 simultaneous connections for a given server per IP (If I remember correctly). and that would create issues if there was a group larger than 5 and all had to be connected. Perhaps this could be resolved by only using one connection to the server instead of a connection for every player, but that is a restriction in the rustplus.js that rustplusplus is currently using.
