### ISSUE TITLE
memory leak 

### ISSUE THREAD

**Issue by C74K** [alexemanuelol/rustPlusPlus#87]
how to fix memory leak on my vps i have memory limit and bot on server restart create memory leak and vps rules kill bot becose bot use more then 1 gigabyte ram.

**Comment by alexemanuelol** [comment]
A quick fix would be to either upgrade your VPS, or restart the bot every now and then.

**Comment by psykzz** [comment]
What about a long term fix?
Could we look into saving the image to disk instead of keeping it in memory.
We can then load it during the check when seeing if the map has wiped / changed.

Really we only need to do that on connected, or if a command requests it.

Not sure we can close it until we look into those solutions.
